### ISSUE TITLE
Wrong charset of changed HTML

### ISSUE THREAD

**Issue by dfranek-pix** [aem-vite/vite-aem-plugin#8]
### Describe the bug

When the HTML is modified the `Content-Type` header is missing the charset. This leads to an incorrect rendering of the page:
![grafik](https://github.com/aem-vite/vite-aem-plugin/assets/138687849/77ce9a6b-411d-43e6-9dcf-b2acd90160fd)

The error is in this line:
https://github.com/aem-vite/vite-aem-plugin/blob/cbc7c413b321d519acdfb0bb2aeb0887e2cebf65/src/helpers.ts#L156

This should be changed to `text/html;charset=utf-8` (or whatever the server sends)

This error also exists in the version for Vite 4, if possible it would be great if it cloud be fixed there also.

**Comment by cshawaus** [comment]
@dfranek-pix Thanks for raising this issue. This is fixed in v5.0.3.
